site_name: Typhoid immune dynamics
copyright: Institute for Disease Modeling &copy 
repo_url: https://github.com/famulare/typhoid-immune-dynamics
repo_name: famulare/typhoid-immune-dynamics

extra_css:
  - stylesheets/extra.css
  
plugins:
  - awesome-nav
  - search
  - blog:
      post_readtime: TRUE
  - rss: 
      enabled: !ENV [CI, false]
      use_git: false
      match_path: blog/posts/.*
      date_from_meta:
        as_creation: date
      categories:
        - categories
  - open-in-new-tab             # https://github.com/squidfunk/mkdocs-material/discussions/3660#discussioncomment-5434673
  - git-revision-date-localized:
      enable_creation_date: true
  - git-committers:
      repository: famulare/typhoid-immune-dynamics
      branch: main
  
theme: 
  name: material
  favicon: img/favicon.ico
  logo: img/IDM_white.png
  icon:
    repo: fontawesome/brands/github
  palette:
    scheme: idm
  features:
  - navigation.instant
  - navigation.sections
  - navigation.path
  - navigation.tabs
  - navigation.tabs.sticky
  - toc.integrate
  - navigation.top
  - search.suggest
  - search.highlight
  - search.share

extra:
  generator: false
      
